default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fish
  password: fish-psql
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_udemy_r7_development

test:
  <<: *default
  database: rails_udemy_r7_test

production:
  <<: *default
  database: rails_udemy_r7_production
  username: fish
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>
